openapi: 3.1.0
info:
  version: 1.0.0
  title: Tasks_Manager app✅
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Personal Task's Manager app
  contact:
    name:  Task_Manager app. Technical Support
    url: 🌐 https://github.com/BilousPM/task-manager-backend
    email: 📧  bilouspm@gmail.com
    x-note: 🌐  Task_Manager app - https://task-manager-backend-y4a1.onrender.com
tags:
  - name: Auth
    description: Auth operations.
  - name: User
    description: User's operation.
  - name: Support
    description: Support operation.
  - name: Boards
    description: Board operation.
  - name: Column
    description: Columns operation.
  - name: Cards
    description: Cards operations.
servers:
  - url: http://localhost:3000
  - url: https://task-manager-backend-y4a1.onrender.com
paths:
  # Auth
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  # User
  /user/current:
    get:
      $ref: ../swagger/paths/user/getCurrent.yaml
  /user/profile:
    patch:
      $ref: '../swagger/paths/user/updateProfile.yaml'
  /user/theme:
    patch:
      $ref: '../swagger/paths/user/changeTheme.yaml'
  /user/delete-user:
    delete:
      $ref: '../swagger/paths/user/deleteUser.yaml'
  # Support
  /support/send-message:
    post:
      $ref: '../swagger/paths/support/support.yaml'
  # Boards
  /boards:
    post:
      $ref: '../swagger/paths/boards/createBoard.yaml'
  /boards/{boardId}:
    get:
      $ref: '../swagger/paths/boards/{id}/getBoardById.yaml'
    patch:
      $ref: '../swagger/paths/boards/{id}/updateBoard.yaml'
    delete:
      $ref: '../swagger/paths/boards/{id}/deleteBoard.yaml'
  # Columns
  /columns/{boardId}:
    post:
      $ref: '../swagger/paths/columns/crateColumn.yaml'
  /columns/{columnId}:
    patch:
      $ref: '../swagger/paths/columns/updateColumn.yaml'
    delete:
      $ref: '../swagger/paths/columns/deleteColumn.yaml'
  # Cards
  /cards/{columnId}:
    post:
      $ref: '../swagger/paths/cards/{columnId}/post.yaml'
  /cards/{cardId}:
    patch:
      $ref: '../swagger/paths/cards/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/cards/{id}/delete.yaml'
  /cards/replace/{cardId}:
    patch:
      $ref: '../swagger/paths/cards/{id}/replace.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
